name: neurodrive
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.1.0
  device_preview: ^1.3.1
  provider: ^6.1.2
  http: ^1.6.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4

  # Seguridad moderna y compatible
  screen_protector: ^1.5.1
  safe_device: ^1.1.6
  camera: ^0.12.0+1
  google_mlkit_face_detection: ^0.13.2
  permission_handler: ^12.0.3
  # Paquete para reproducción de audio
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Herramienta para generar iconos de launcher
  flutter_launcher_icons: ^0.13.1

# Configuración del icono de la aplicación
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
